---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian12
    image: debian:bookworm
    pre_build_image: false
    dockerfile: Dockerfile.debian.j2
provisioner:
  name: ansible
verifier:
  name: ansible
