---
- name: Add Tailscale repository key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/bionic.gpg
    state: present
- name: Add Tailscale repository
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu bionic main
    filename: tailscale
    state: present
- name: Install packages
  apt:
    name:
      - tailscale
    state: present
- name: Connect machine to your Tailscale network
  command: tailscale up -authkey {{ tailscale_authkey }}
