---
- name: Setup Ubuntu
  ansible.builtin.include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Setup Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- name: Install Tailscale (version)
  ansible.builtin.package:
    name: tailscale={{ tailscale_version }}
    state: present
  when: tailscale_version is defined
  become: true

- name: Install Tailscale (latest)
  ansible.builtin.package:
    name: tailscale
    state: present
  when: tailscale_version is not defined
  become: true

- name: Connect machine to your Tailscale network
  ansible.builtin.command: tailscale up -authkey {{ tailscale_authkey }}
  when: tailscale_authkey is defined
  changed_when: false
  become: true
