---
- include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: setup-Debian.yml
  when: ansible_distribution == 'Debian'

- name: Install Tailscale package
  package:
    name: tailscale={{ tailscale_version }}
    state: present
  become: true

- name: Connect machine to your Tailscale network
  command: tailscale up -authkey {{ tailscale_authkey }}
  changed_when: no
  become: true
