---
- name: tailscale repository key
  apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/bionic.gpg
    state: present
- name: tailscale repository
  apt_repository:
    repo: deb https://pkgs.tailscale.com/stable/ubuntu bionic main
    filename: tailscale
    state: present
- name: install packages
  apt:
    name:
      - tailscale
    state: present
- debug: msg="run tailscale up"
