---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - ca-certificates
    state: present
  become: true

- name: Download Tailscale repository key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"
  become: true

- name: Download Tailscale repository
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: "0644"
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true
